# День 00 – Сбор и очистка данных

 Добро пожаловать в Jupyter Notebook! Это тот инструмент, в котором дата сайентисты проводят больше всего времени, работая с данными при помощи кода на Python. Здесь очень удобно работать в интерактивном режиме, запуская отдельные ячейки, а не весь код сразу и полностью. Тут же можно делать и отчеты, поскольку помимо кода, здесь удобно строить графики и писать текст.

Мы понимаем, что вы не программисты и скорее всего не планируете ими стать, поэтому насколько это возможно мы будем сопровождать такие ноутбуки комментариями и полезными командами, которые могут вам пригодиться для решения задачи. Но естественно здесь будет не всё: что-то вам придется поискать самостоятельно в интернете. Такова уж методология Школы 21, и она приносит свои плоды.

## 0. Импорт библиотек

Библиотека – это по сути набор полезных функций и методов, которые написали одни программисты, а другие программисты могут уже не писать их с нуля, а пользоваться готовыми. Например, вы хотите посчитать среднее арифметическое значение по ряду. Вы можете самостоятельно написать код, который посчитает сумму по ряду и поделит на количество элементов в ряду, а можете импортировать библиотеку, где уже есть эта функция и воспользоваться ею. Это сэкономит вам время, силы, и код будет менее объемным.

Ниже мы импортируем широко используемую библиотеку Pandas. В ней есть много полезных функций для работы с табличными данными. Почти Excel, только взаимодействие с ним через код на Python. Мы будем пользоваться этой библиотекой в течение всего курса.

In [1]:
import pandas as pd #мы будем часто пользоваться методами этой библиотеки, поэтому введем для нее сокращенное название – pd
import numpy as np

Давайте познакомимся с библиотекой Pandas. Pandas - это библиотека языка Python, который предоставляет быстрые, гибкие и выразительные структуры данных, разработанные для того, чтобы сделать работу с табличными данными простой и интуитивно понятной. 

## 1. Загрузка данных

In [81]:
import pandas as pd #мы будем часто пользоваться методами этой библиотеки, поэтому введем для нее сокращенное название – pd
import numpy as np

df1 = pd.read_csv('/Users/npk-s80-1/Desktop/day00/dataset/part_01.csv') #указываем путь к файлу
df1.head(10) #посмотрим несколько первых строк получившегося датафрейма

ID  AMOUNT_RUB_ATM_PRC  AMOUNT_RUB_CLO_PRC  AMOUNT_RUB_NAS_PRC  \
0  358628            0.914453            0.003802            0.000000   
1  528730                 NaN                 NaN                 NaN   
2  160451            0.989403            0.000239            0.000992   
3  210467            0.561584            0.000000            0.016932   
4  292486            0.201789            0.147567            0.033131   
5  211110            0.909531            0.051183            0.000000   
6  333131            0.485581            0.008142            0.000000   
7  549028            0.738620            0.020976            0.005257   
8  274285            0.998698            0.000000            0.000000   
9  577671            0.000000            0.000000            0.036643   

   AMOUNT_RUB_SUP_PRC  CNT_TRAN_ATM_TENDENCY1M  CNT_TRAN_ATM_TENDENCY3M  \
0            0.030183                 0.216216                 0.540541   
1                 NaN                      NaN                      NaN   
2            0.000765                      NaN                 0.312500   
3            0.009256                      NaN                 0.600000   
4            0.165119                 0.142857                 1.000000   
5            0.023359                 0.238095                 0.571429   
6            0.045329                 0.400000                 0.700000   
7            0.074851                 0.260870                 0.478261   
8            0.000000                 0.653846                 1.000000   
9            0.150664                      NaN                      NaN   

   CNT_TRAN_AUT_TENDENCY1M  CNT_TRAN_AUT_TENDENCY3M  CNT_TRAN_CLO_TENDENCY1M  \
0                 0.333333                 0.333333                      NaN   
1                      NaN                      NaN                      NaN   
2                      NaN                 0.333333                      NaN   
3                      NaN                      NaN                      NaN   
4                      NaN                 0.400000                 0.266667   
5                      NaN                      NaN                      NaN   
6                 0.500000                 0.666667                 0.285714   
7                 0.500000                 0.625000                 1.000000   
8                      NaN                      NaN                      NaN   
9                      NaN                      NaN                      NaN   

   ...  SUM_TRAN_CLO_TENDENCY3M  SUM_TRAN_MED_TENDENCY1M  \
0  ...                      NaN                      NaN   
1  ...                      NaN                      NaN   
2  ...                      NaN                      NaN   
3  ...                      NaN                      NaN   
4  ...                 0.401480                 0.129829   
5  ...                      NaN                      NaN   
6  ...                 0.186795                 0.151151   
7  ...                 1.000000                      NaN   
8  ...                      NaN                      NaN   
9  ...                      NaN                      NaN   

   SUM_TRAN_MED_TENDENCY3M  SUM_TRAN_SUP_TENDENCY1M  SUM_TRAN_SUP_TENDENCY3M  \
0                      NaN                 0.004301                 0.538223   
1                      NaN                      NaN                      NaN   
2                 1.000000                      NaN                 0.037963   
3                      NaN                      NaN                      NaN   
4                 0.586312                 0.122523                 0.640830   
5                      NaN                      NaN                 0.588211   
6                 0.151773                 0.378124                 0.525558   
7                      NaN                 0.139912                 0.571189   
8                      NaN                      NaN                      NaN   
9                      NaN         

In [80]:
import pandas as pd #мы будем часто пользоваться методами этой библиотеки, поэтому введем для нее сокращенное название – pd
import numpy as np

df1 = pd.read_csv('/Users/veiledsl/Downloads/Archive/part_01.csv') #указываем путь к файлу
df1.head() #посмотрим несколько первых строк получившегося датафрейма

FileNotFoundError: [Errno 2] No such file or directory: '/Users/veiledsl/Downloads/Archive/part_01.csv'

Если всё получилось, то вы увидите небольшой кусок таблицы: шапку, первые пять строчек

Загрузим еще несколько датасетов

In [7]:
df2 = pd.read_csv('/Users/npk-s80-1/Desktop/day00/dataset/dataset_2.csv')

In [8]:
df2.head()

ID  AMOUNT_RUB_SUP_PRC  CNT_TRAN_ATM_TENDENCY1M APP_COMP_TYPE
0  358628            0.030183                 0.216216           NaN
1  528730                 NaN                      NaN       PRIVATE
2  160451            0.000765                      NaN         STATE
3  210467            0.009256                      NaN       PRIVATE
4  211110            0.023359                 0.238095       PRIVATE

In [5]:
df3 = pd.read_csv('/Users/npk-s80-1/Desktop/day00/dataset/dataset_3.csv') #указываем путь к файлу

In [6]:
df3.head()

ID  AMOUNT_RUB_ATM_PRC  AMOUNT_RUB_CLO_PRC  AMOUNT_RUB_NAS_PRC  \
0  274285            0.998698                 0.0            0.000000   
1  577671            0.000000                 0.0            0.036643   

   AMOUNT_RUB_SUP_PRC  CNT_TRAN_ATM_TENDENCY1M  APP_COMP_TYPE  
0            0.000000                 0.653846            NaN  
1            0.150664                      NaN            NaN

## 2. Полезные команды

Ниже мы покажем несколько полезных команд, которые вам могут пригодиться для выполнения сегодняшнего задания.

1. Узнать **названия полей** в датафрейме.

In [9]:
df1.columns

Index(['ID', 'AMOUNT_RUB_ATM_PRC', 'AMOUNT_RUB_CLO_PRC', 'AMOUNT_RUB_NAS_PRC',
       'AMOUNT_RUB_SUP_PRC', 'CNT_TRAN_ATM_TENDENCY1M',
       'CNT_TRAN_ATM_TENDENCY3M', 'CNT_TRAN_AUT_TENDENCY1M',
       'CNT_TRAN_AUT_TENDENCY3M', 'CNT_TRAN_CLO_TENDENCY1M',
       'CNT_TRAN_CLO_TENDENCY3M', 'CNT_TRAN_MED_TENDENCY1M',
       'CNT_TRAN_MED_TENDENCY3M', 'CNT_TRAN_SUP_TENDENCY1M',
       'CNT_TRAN_SUP_TENDENCY3M', 'SUM_TRAN_ATM_TENDENCY1M',
       'SUM_TRAN_ATM_TENDENCY3M', 'SUM_TRAN_AUT_TENDENCY1M',
       'SUM_TRAN_AUT_TENDENCY3M', 'SUM_TRAN_CLO_TENDENCY1M',
       'SUM_TRAN_CLO_TENDENCY3M', 'SUM_TRAN_MED_TENDENCY1M',
       'SUM_TRAN_MED_TENDENCY3M', 'SUM_TRAN_SUP_TENDENCY1M',
       'SUM_TRAN_SUP_TENDENCY3M', 'TRANS_AMOUNT_TENDENCY3M',
       'TRANS_CNT_TENDENCY3M', 'TRANS_COUNT_ATM_PRC', 'TRANS_COUNT_NAS_PRC',
       'TRANS_COUNT_SUP_PRC'],
      dtype='object')

2. Присоединить датафрейм **справа**:

In [11]:
df4 = df1.merge(df2, left_on='ID', right_on='ID') # выбираем ID в качестве ключа, по которому датафреймы будут объединяться

In [12]:
df4.head()

ID  AMOUNT_RUB_ATM_PRC  AMOUNT_RUB_CLO_PRC  AMOUNT_RUB_NAS_PRC  \
0  358628            0.914453            0.003802            0.000000   
1  528730                 NaN                 NaN                 NaN   
2  160451            0.989403            0.000239            0.000992   
3  210467            0.561584            0.000000            0.016932   
4  211110            0.909531            0.051183            0.000000   

   AMOUNT_RUB_SUP_PRC_x  CNT_TRAN_ATM_TENDENCY1M_x  CNT_TRAN_ATM_TENDENCY3M  \
0              0.030183                   0.216216                 0.540541   
1                   NaN                        NaN                      NaN   
2              0.000765                        NaN                 0.312500   
3              0.009256                        NaN                 0.600000   
4              0.023359                   0.238095                 0.571429   

   CNT_TRAN_AUT_TENDENCY1M  CNT_TRAN_AUT_TENDENCY3M  CNT_TRAN_CLO_TENDENCY1M  \
0                 0.333333                 0.333333                      NaN   
1                      NaN                      NaN                      NaN   
2                      NaN                 0.333333                      NaN   
3                      NaN                      NaN                      NaN   
4                      NaN                      NaN                      NaN   

   ...  SUM_TRAN_SUP_TENDENCY1M  SUM_TRAN_SUP_TENDENCY3M  \
0  ...                 0.004301                 0.538223   
1  ...                      NaN                      NaN   
2  ...                      NaN                 0.037963   
3  ...                      NaN                      NaN   
4  ...                      NaN                 0.588211   

   TRANS_AMOUNT_TENDENCY3M  TRANS_CNT_TENDENCY3M  TRANS_COUNT_ATM_PRC  \
0                 0.612532              0.338028             0.521127   
1                      NaN                   NaN                  NaN   
2                 0.200819              0.208955             0.477612   
3                 0.609531              0.458333             0.208333   
4                 0.500233              0.509434             0.792453   

   TRANS_COUNT_NAS_PRC  TRANS_COUNT_SUP_PRC  AMOUNT_RUB_SUP_PRC_y  \
0             0.000000             0.211268              0.030183   
1                  NaN                  NaN                   NaN   
2             0.164179             0.059701              0.000765   
3             0.041667             0.083333              0.009256   
4             0.000000             0.094340              0.023359   

   CNT_TRAN_ATM_TENDENCY1M_y  APP_COMP_TYPE  
0                   0.216216            NaN  
1                        NaN        PRIVATE  
2                        NaN          STATE  
3                        NaN        PRIVATE  
4                   0.238095        PRIVATE  

[5 rows x 33 columns]

2. Присоединить датафрейм **снизу**:

In [13]:
df5 = pd.concat([df2, df4], ignore_index=True)
df5.head()

ID  AMOUNT_RUB_SUP_PRC  CNT_TRAN_ATM_TENDENCY1M APP_COMP_TYPE  \
0  358628            0.030183                 0.216216           NaN   
1  528730                 NaN                      NaN       PRIVATE   
2  160451            0.000765                      NaN         STATE   
3  210467            0.009256                      NaN       PRIVATE   
4  211110            0.023359                 0.238095       PRIVATE   

   AMOUNT_RUB_ATM_PRC  AMOUNT_RUB_CLO_PRC  AMOUNT_RUB_NAS_PRC  \
0                 NaN                 NaN                 NaN   
1                 NaN                 NaN                 NaN   
2                 NaN                 NaN                 NaN   
3                 NaN                 NaN                 NaN   
4                 NaN                 NaN                 NaN   

   AMOUNT_RUB_SUP_PRC_x  CNT_TRAN_ATM_TENDENCY1M_x  CNT_TRAN_ATM_TENDENCY3M  \
0                   NaN                        NaN                      NaN   
1                   NaN                        NaN                      NaN   
2                   NaN                        NaN                      NaN   
3                   NaN                        NaN                      NaN   
4                   NaN                        NaN                      NaN   

   ...  SUM_TRAN_MED_TENDENCY3M  SUM_TRAN_SUP_TENDENCY1M  \
0  ...                      NaN                      NaN   
1  ...                      NaN                      NaN   
2  ...                      NaN                      NaN   
3  ...                      NaN                      NaN   
4  ...                      NaN                      NaN   

   SUM_TRAN_SUP_TENDENCY3M  TRANS_AMOUNT_TENDENCY3M  TRANS_CNT_TENDENCY3M  \
0                      NaN                      NaN                   NaN   
1                      NaN                      NaN                   NaN   
2                      NaN                      NaN                   NaN   
3                      NaN                      NaN                   NaN   
4                      NaN                      NaN                   NaN   

   TRANS_COUNT_ATM_PRC  TRANS_COUNT_NAS_PRC  TRANS_COUNT_SUP_PRC  \
0                  NaN                  NaN                  NaN   
1                  NaN                  NaN                  NaN   
2                  NaN                  NaN                  NaN   
3                  NaN                  NaN                  NaN   
4                  NaN                  NaN                  NaN   

   AMOUNT_RUB_SUP_PRC_y  CNT_TRAN_ATM_TENDENCY1M_y  
0                   NaN                        NaN  
1                   NaN                        NaN  
2                   NaN                        NaN  
3                   NaN                        NaN  
4                   NaN                        NaN  

[5 rows x 35 columns]

Теперь перейдем к этапу очистки данных. Напомним: вам нужно значения текстовых полей привести к единообразию. То есть слова, написанные немного по-разному, привести к одному варианту их написания.

Ниже вы найдете перечень команд, которые помогут справиться с этим заданием по очистке полученного на предыдущем шаге датасета.

4. Команда, которая поможет вам выявить, какие же поля являются текстовыми.

In [14]:
df5.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 35 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   ID                         12 non-null     int64  
 1   AMOUNT_RUB_SUP_PRC         5 non-null      float64
 2   CNT_TRAN_ATM_TENDENCY1M    3 non-null      float64
 3   APP_COMP_TYPE              8 non-null      object 
 4   AMOUNT_RUB_ATM_PRC         5 non-null      float64
 5   AMOUNT_RUB_CLO_PRC         5 non-null      float64
 6   AMOUNT_RUB_NAS_PRC         5 non-null      float64
 7   AMOUNT_RUB_SUP_PRC_x       5 non-null      float64
 8   CNT_TRAN_ATM_TENDENCY1M_x  3 non-null      float64
 9   CNT_TRAN_ATM_TENDENCY3M    5 non-null      float64
 10  CNT_TRAN_AUT_TENDENCY1M    2 non-null      float64
 11  CNT_TRAN_AUT_TENDENCY3M    3 non-null      float64
 12  CNT_TRAN_CLO_TENDENCY1M    1 non-null      float64
 13  CNT_TRAN_CLO_TENDENCY3M    1 non-null      float64
 

5. Команда, позволяющая посмотреть **список уникальных значений** в столбце:

In [15]:
df5.APP_COMP_TYPE.unique() 

array([nan, 'PRIVATE', 'STATE'], dtype=object)

 Она же, только представленная **в виде списка**. Бывает полезной, когда уникальных значений слишком много и в предыдущем варианте показываются не все из них. Плюс результат не содержит всякой лишней информации.

In [16]:
list(df5.APP_COMP_TYPE.unique()) 

[nan, 'PRIVATE', 'STATE']

6. Команда, которая позволяет привести все значения признака в **в нижний регистр**:

In [17]:
df5.APP_COMP_TYPE = df5.APP_COMP_TYPE.str.lower() #недостаточно просто применить метод lower к столбцу, нужно как бы его перезаписать 

In [132]:
df5.dtypes

ID                             int64
AMOUNT_RUB_SUP_PRC           float64
CNT_TRAN_ATM_TENDENCY1M      float64
APP_COMP_TYPE                 object
AMOUNT_RUB_ATM_PRC           float64
AMOUNT_RUB_CLO_PRC           float64
AMOUNT_RUB_NAS_PRC           float64
AMOUNT_RUB_SUP_PRC_x         float64
CNT_TRAN_ATM_TENDENCY1M_x    float64
CNT_TRAN_ATM_TENDENCY3M      float64
CNT_TRAN_AUT_TENDENCY1M      float64
CNT_TRAN_AUT_TENDENCY3M      float64
CNT_TRAN_CLO_TENDENCY1M      float64
CNT_TRAN_CLO_TENDENCY3M      float64
CNT_TRAN_MED_TENDENCY1M      float64
CNT_TRAN_MED_TENDENCY3M      float64
CNT_TRAN_SUP_TENDENCY1M      float64
CNT_TRAN_SUP_TENDENCY3M      float64
SUM_TRAN_ATM_TENDENCY1M      float64
SUM_TRAN_ATM_TENDENCY3M      float64
SUM_TRAN_AUT_TENDENCY1M      float64
SUM_TRAN_AUT_TENDENCY3M      float64
SUM_TRAN_CLO_TENDENCY1M      float64
SUM_TRAN_CLO_TENDENCY3M      float64
SUM_TRAN_MED_TENDENCY1M      float64
SUM_TRAN_MED_TENDENCY3M      float64
SUM_TRAN_SUP_TENDENCY1M      float64
S

In [18]:
list(df5.APP_COMP_TYPE.unique()) 

[nan, 'private', 'state']

7. Команда, которая позволяет заменить значения в столбце на другие значения:

In [19]:
df5.APP_COMP_TYPE.replace('state','гос',inplace=True) 

In [20]:
list(df5.APP_COMP_TYPE.unique()) 

[nan, 'private', 'гос']

8. Команда, которая позволяет **отсортировать** значения в списке (может пригодиться, чтобы посмотреть на длинный список):

In [27]:
mylist = list(df5.APP_COMP_TYPE.unique())
mylist.sort()

TypeError: '<' not supported between instances of 'str' and 'float'

После нее выведется ошибка, потому что в списке есть nan – специальный тип данных, обозначающий пустое значение. По этой причине не может отсортировать список: все значения текстовые, а одно значение nan. Нужно этот nan удалить из списка уникальных значений, чтобы не мешался. Не будем вдаваться в подробности почему ниже команда выглядит именно так. Она приводит нас к результату.

In [22]:
spisok = [x for x in list(df5.APP_COMP_TYPE.unique()) if x == x]
spisok.sort()
spisok

['private', 'гос']

9. Команда, которая помогает **удалить из текстового поля числовые значения**, короткие значения, значения, где есть знаки препинания.

In [28]:
df5.APP_COMP_TYPE.where(df5.APP_COMP_TYPE.str.replace(' ','').str.isalpha(), np.nan, inplace=True) 

Если вам не хватает команд, представленных в этом ноутбуке, то вы можете **самостоятельно воспользоваться поиском в Google**.

    "pandas how to save a csv-file with header"
    
    "pandas how to save a csv-file with header"
     
    "pandas how to compare values of two columns"

## 3. Самостоятельная часть

Ниже вам нужно самим собрать целиком датасет из разрозненных кусков и почистить датасет в части текстовых полей.

### 3.1 Объединение датасета
Вам нужно собрать полный датасет, собранный из частей датасета всех участников.
1. Датасет должен содержать в шапке названия полей.
2. Датасет не должен содержать лишних столбцов – только те, что были представлены в частях датасета.
3. Датасет должен быть отсортирован по возрастанию значений поля `ID`.
4. В датасете не должно быть дублирующихся строк и столбцов.

In [1]:
import pandas as pd #мы будем часто пользоваться методами этой библиотеки, поэтому введем для нее сокращенное название – pd
import numpy as np

data1 = pd.read_csv('/Users/npk-s80-1/Desktop/day00/dataset/part_01.csv')
data2 = pd.read_csv('/Users/npk-s80-1/Desktop/day00/dataset/part_02.csv')
data3 = pd.read_csv('/Users/npk-s80-1/Desktop/day00/dataset/part_03.csv')
data4 = pd.read_csv('/Users/npk-s80-1/Desktop/day00/dataset/part_04.csv')
data5 = pd.read_csv('/Users/npk-s80-1/Desktop/day00/dataset/part_05.csv')
data6 = pd.read_csv('/Users/npk-s80-1/Desktop/day00/dataset/part_06.csv')
data7 = pd.read_csv('/Users/npk-s80-1/Desktop/day00/dataset/part_07.csv')
data8 = pd.read_csv('/Users/npk-s80-1/Desktop/day00/dataset/part_08.csv')
data9 = pd.read_csv('/Users/npk-s80-1/Desktop/day00/dataset/part_09.csv')
data10 = pd.read_csv('/Users/npk-s80-1/Desktop/day00/dataset/part_10.csv')
data11 = pd.read_csv('/Users/npk-s80-1/Desktop/day00/dataset/part_11.csv')
data12 = pd.read_csv('/Users/npk-s80-1/Desktop/day00/dataset/part_12.csv')
data12.head()

ID  CNT_ACCEPTS_MTP  CNT_ACCEPTS_TK  PRC_ACCEPTS_A_AMOBILE  \
0  367218              0.0             0.0                    0.0   
1  313965              0.0             0.0                    0.0   
2  484369              NaN             NaN                    NaN   
3  162251              NaN             NaN                    NaN   
4  362543              NaN             NaN                    NaN   

   PRC_ACCEPTS_A_ATM  PRC_ACCEPTS_A_EMAIL_LINK  PRC_ACCEPTS_A_MTP  \
0                0.0                       0.0                0.0   
1                0.0                       0.0                0.0   
2                NaN                       NaN                NaN   
3                NaN                       NaN                NaN   
4                NaN                       NaN                NaN   

   PRC_ACCEPTS_A_POS  PRC_ACCEPTS_A_TK  PRC_ACCEPTS_MTP  PRC_ACCEPTS_TK  
0                0.0               0.0              0.0             0.0  
1                0.0               0.0              0.0             0.0  
2                NaN               NaN              NaN             NaN  
3                NaN               NaN              NaN             NaN  
4                NaN               NaN              NaN             NaN

In [4]:
data_1_9 = pd.concat([data1, data9], ignore_index=True)
data_2_11 = pd.concat([data2, data11], ignore_index=True)
data_3_8 = pd.concat([data3, data8], ignore_index=True)
data_4_7 = pd.concat([data4, data7], ignore_index=True)
data_6_10 = pd.concat([data6, data10], ignore_index=True)
data_5_12 = pd.concat([data5, data12], ignore_index=True)


In [5]:
data_itog = data_1_9.merge(data_2_11, how='left', sort=True, left_on='ID', right_on='ID')
data_itog = data_itog.merge(data_3_8, how='left', sort=True, left_on='ID', right_on='ID')
data_itog = data_itog.merge(data_4_7, how='left', sort=True, left_on='ID', right_on='ID')
data_itog = data_itog.merge(data_6_10, how='left', sort=True, left_on='ID', right_on='ID')
data_itog = data_itog.merge(data_5_12, how='left', sort=True, left_on='ID', right_on='ID')
data_itog.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 355190 entries, 0 to 355189
Data columns (total 116 columns):
 #    Column                       Dtype  
---   ------                       -----  
 0    ID                           int64  
 1    AMOUNT_RUB_ATM_PRC           float64
 2    AMOUNT_RUB_CLO_PRC           float64
 3    AMOUNT_RUB_NAS_PRC           float64
 4    AMOUNT_RUB_SUP_PRC           float64
 5    CNT_TRAN_ATM_TENDENCY1M      float64
 6    CNT_TRAN_ATM_TENDENCY3M      float64
 7    CNT_TRAN_AUT_TENDENCY1M      float64
 8    CNT_TRAN_AUT_TENDENCY3M      float64
 9    CNT_TRAN_CLO_TENDENCY1M      float64
 10   CNT_TRAN_CLO_TENDENCY3M      float64
 11   CNT_TRAN_MED_TENDENCY1M      float64
 12   CNT_TRAN_MED_TENDENCY3M      float64
 13   CNT_TRAN_SUP_TENDENCY1M      float64
 14   CNT_TRAN_SUP_TENDENCY3M      float64
 15   SUM_TRAN_ATM_TENDENCY1M      float64
 16   SUM_TRAN_ATM_TENDENCY3M      float64
 17   SUM_TRAN_AUT_TENDENCY1M      float64
 18   SUM_TRAN_AUT_TENDENCY3

5. Выведете первые 10 строк объединенного датасета

In [6]:
data_itog.head()

ID  AMOUNT_RUB_ATM_PRC  AMOUNT_RUB_CLO_PRC  AMOUNT_RUB_NAS_PRC  \
0  146841            1.000000            0.000000                 0.0   
1  146842            0.410691            0.041033                 0.0   
2  146843            0.925140            0.006915                 0.0   
3  146844            1.000000            0.000000                 0.0   
4  146845            1.000000            0.000000                 0.0   

   AMOUNT_RUB_SUP_PRC  CNT_TRAN_ATM_TENDENCY1M  CNT_TRAN_ATM_TENDENCY3M  \
0            0.000000                 0.101695                 0.406780   
1            0.244678                 0.166667                 0.333333   
2            0.000000                 0.133333                 0.366667   
3            0.000000                      NaN                      NaN   
4            0.000000                 0.172414                 0.620690   

   CNT_TRAN_AUT_TENDENCY1M  CNT_TRAN_AUT_TENDENCY3M  CNT_TRAN_CLO_TENDENCY1M  \
0                      NaN                      NaN                      NaN   
1                 0.166667                 0.666667                      NaN   
2                      NaN                      NaN                      NaN   
3                      NaN                      NaN                      NaN   
4                      NaN                      NaN                      NaN   

   ...  CNT_ACCEPTS_MTP  CNT_ACCEPTS_TK  PRC_ACCEPTS_A_AMOBILE  \
0  ...              NaN             NaN                    NaN   
1  ...              NaN             NaN                    NaN   
2  ...              0.0             0.0                    0.0   
3  ...              NaN             NaN                    NaN   
4  ...              NaN             NaN                    NaN   

   PRC_ACCEPTS_A_ATM  PRC_ACCEPTS_A_EMAIL_LINK  PRC_ACCEPTS_A_MTP  \
0                NaN                       NaN                NaN   
1                NaN                       NaN                NaN   
2                0.0                       0.0                0.0   
3                NaN                       NaN                NaN   
4                NaN                       NaN                NaN   

   PRC_ACCEPTS_A_POS  PRC_ACCEPTS_A_TK  PRC_ACCEPTS_MTP  PRC_ACCEPTS_TK  
0                NaN               NaN              NaN             NaN  
1                NaN               NaN              NaN             NaN  
2                0.0               0.0              0.0             0.0  
3                NaN               NaN              NaN             NaN  
4                NaN               NaN              NaN             NaN  

[5 rows x 116 columns]

6. Выведите количество столбцов и колонок в объединенном датасете

In [171]:
print(
    "количество столбцов: "+str(len(data_itog.columns))+
    "\nколичество строк: "+str(len(data_itog.index)))

количество столбцов: 116
количество строк: 355190


7. Проверьте датасеты на отсутствие дубликатов

In [172]:
data_itog.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...  
355185    False
355186    False
355187    False
355188    False
355189    False
Length: 355190, dtype: bool

### 3.2. Очистка текстовых данных
Теперь можно приступать к очистке данных. Для этого нужно:
1. Найти в получившемся датасете все поля, которые являются текстовыми.
2. Привести их значения к нижнему регистру.
3. В тех полях, где есть одновременно русское и английское написание одного и того же слова, оставить только русское (заменить английское на русское). Это условие не применять к полю `CLNT_JOB_POSITION`. Это будет чересчур даже для нашего курса :)
4. Если текстовое значение состоит только из “` `“ (пробел), то его заменить на `NaN` (пустое значение, а не строку 'NaN').
5. Если в текстовом значении есть цифры (телефон, дата рождения и др.), то всё значение текстового поля тоже заменить на `NaN`. Поле `PACK` оставить в исходном виде. Оно отвечает за пакет услуг клиента, и нам эта информация может быть важной. Затирать ее на пустые значения было бы опрометчиво.
6. Если есть столбцы, которые абсолютно идентичны по своим значениям для одних и тех же строк, то оставить только тот столбец, который идет первее. Речь идет только о текстовых полях.

In [8]:
data_itog.APP_CAR = data_itog.APP_CAR.str.lower()
data_itog.APP_COMP_TYPE = data_itog.APP_COMP_TYPE.str.lower()
data_itog.APP_DRIVING_LICENSE = data_itog.APP_DRIVING_LICENSE.str.lower()
data_itog.APP_EDUCATION = data_itog.APP_EDUCATION.str.lower()
data_itog.APP_EMP_TYPE = data_itog.APP_EMP_TYPE.str.lower()
data_itog.APP_KIND_OF_PROP_HABITATION = data_itog.APP_KIND_OF_PROP_HABITATION.str.lower()
data_itog.APP_MARITAL_STATUS = data_itog.APP_MARITAL_STATUS.str.lower()
data_itog.APP_POSITION_TYPE = data_itog.APP_POSITION_TYPE.str.lower()
data_itog.APP_TRAVEL_PASS = data_itog.APP_TRAVEL_PASS.str.lower()
data_itog.CLNT_JOB_POSITION = data_itog.CLNT_JOB_POSITION.str.lower()
data_itog.CLNT_JOB_POSITION_TYPE = data_itog.CLNT_JOB_POSITION_TYPE.str.lower()
data_itog.CLNT_TRUST_RELATION = data_itog.CLNT_TRUST_RELATION.str.lower()
data_itog.PACK = data_itog.PACK.str.lower()

In [9]:
data_itog.to_csv('/Users/npk-s80-1/Desktop/day00/dataset/data_itog.csv', header=True, index=False)

In [10]:
data_itog.APP_CAR.unique()

array([nan, 'n', 'y'], dtype=object)

In [11]:
data_itog.APP_COMP_TYPE.unique()

array([nan, 'private', 'state', 'ip', 'inter'], dtype=object)

In [12]:
data_itog.APP_DRIVING_LICENSE.unique()

array([nan, 'y', 'n'], dtype=object)

In [13]:
data_itog.APP_EDUCATION.unique()

array([nan, 's', 'hh', 'h', 'ss', 'uh', 'a', 'i', 'us', 'e', 'hi', 'av',
       'ac'], dtype=object)

In [14]:
data_itog.APP_EMP_TYPE.unique()

array([nan, 'private', 'state', 'ip', 'inter'], dtype=object)

In [15]:
data_itog.APP_KIND_OF_PROP_HABITATION.unique()

array([nan, 'so', 'rent', 'other', 'jo', 'nprivat'], dtype=object)

In [16]:
data_itog.APP_MARITAL_STATUS.unique()

array([nan, 'd', 'm', 'v', 't', 'n', ' ', 'w', 'c'], dtype=object)

In [17]:
data_itog.APP_POSITION_TYPE.unique()

array([nan, 'specialist', 'self_empl', 'manager', 'top_manager'],
      dtype=object)

In [18]:
data_itog.APP_TRAVEL_PASS.unique()

array([nan, 'n', 'y'], dtype=object)

In [19]:
data_itog.CLNT_JOB_POSITION_TYPE.unique()

array([nan, 'specialist', 'self_empl', 'manager', 'top_manager'],
      dtype=object)

In [20]:
data_itog.CLNT_TRUST_RELATION.unique()

array([nan, 'mother', 'brother', 'friend', 'sister', 'other', 'relative',
       'daughter', 'son', 'father', 'близкий ро', 'друг', 'отец',
       'сестра', 'сын', 'мать', 'муж', 'брат', 'дальний ро', 'дочь',
       'жена'], dtype=object)

In [21]:
data_itog.PACK.unique()

array(['k01', '102', '105', 'o01', '103', '101', '107', '301', '104',
       '108', '109', 'm01'], dtype=object)

In [22]:
data_itog.CLNT_TRUST_RELATION = data_itog.CLNT_TRUST_RELATION.str.replace('mother', 'мать')

In [23]:
data_itog.CLNT_TRUST_RELATION = data_itog.CLNT_TRUST_RELATION.str.replace('brother', 'брат')

In [24]:
data_itog.CLNT_TRUST_RELATION = data_itog.CLNT_TRUST_RELATION.str.replace('friend', 'друг')

In [25]:
data_itog.CLNT_TRUST_RELATION = data_itog.CLNT_TRUST_RELATION.str.replace('sister', 'сестра')

In [26]:
data_itog.CLNT_TRUST_RELATION = data_itog.CLNT_TRUST_RELATION.str.replace('other', 'дальний ро')

In [27]:
data_itog.CLNT_TRUST_RELATION = data_itog.CLNT_TRUST_RELATION.str.replace('relative', 'близкий ро')

In [28]:
data_itog.CLNT_TRUST_RELATION = data_itog.CLNT_TRUST_RELATION.str.replace('daughter', 'дочь')

In [29]:
data_itog.CLNT_TRUST_RELATION = data_itog.CLNT_TRUST_RELATION.str.replace('son', 'сын')

In [30]:
data_itog.CLNT_TRUST_RELATION = data_itog.CLNT_TRUST_RELATION.str.replace('father', 'отец')

In [31]:
data_itog.CLNT_TRUST_RELATION.unique()

array([nan, 'мать', 'брат', 'друг', 'сестра', 'дальний ро', 'близкий ро',
       'дочь', 'сын', 'отец', 'муж', 'жена'], dtype=object)

7. Выведите количество уникальных значения в полях CLNT_TRUST_RELATION, APP_MARITAL_STATUS, CLNT_JOB_POSITION

In [219]:
data_itog.APP_MARITAL_STATUS.where (data_itog.APP_MARITAL_STATUS.str.isspace()==False, np.nan, inplace=True)

In [220]:
len(data_itog.CLNT_TRUST_RELATION.unique())

12

In [221]:
len(data_itog.APP_MARITAL_STATUS.unique())

8

In [222]:
len(data_itog.CLNT_JOB_POSITION.unique())

14623

In [208]:
data_itog.APP_MARITAL_STATUS.unique()

array([nan, 'd', 'm', 'v', 't', 'n', 'w', 'c'], dtype=object)

In [209]:
for value in data_itog.CLNT_JOB_POSITION.unique():
    print (value)

начальник отдела
nan
генеральный директор
менеджер иао
директор
предприниматель
архитектор
экономист
менеджер
системотехник
медицинский представитель
дистрибьютор
зам. начальника отдела
техник геофизик
специалист
водитель-экспедитор
ген. директор
зам.директора по туризму
специалист по страхованию
главныцй бухгалтер
заместитель генерального директора
продавец
программист
специалист отдела кадров
специалист отдела продаж
заместитель начальника отдела
грузчик-наборщик
звукоинженер
зам. директора по кадровым вопросам
матрос
альпинист
курьер
руководитель направления
художник
индивидуальный предприниматель
лаборант
исполнительный директор
финансовый директор
врач
зам. директора
водитель
маркетолог
врач анестезиолог реаниматолог
водителоь-экспедитор
артдиректор
инженер-программист
разработчик аппаратных средств
редактор сайта gameland.ru
вед.специалист эксперт
бухгалтер
специалист 1-го разряда
администратор
старший тех специалист
мастер механик
дизайнер
ведущий специалист
начальник участка
за

In [210]:
data_itog.CLNT_JOB_POSITION.where (data_itog.CLNT_JOB_POSITION.str.contains('\\d', regex=True)==False, np.nan, inplace=True)

In [211]:
for value in data_itog.CLNT_JOB_POSITION.unique():
    print (value)

начальник отдела
nan
генеральный директор
менеджер иао
директор
предприниматель
архитектор
экономист
менеджер
системотехник
медицинский представитель
дистрибьютор
зам. начальника отдела
техник геофизик
специалист
водитель-экспедитор
ген. директор
зам.директора по туризму
специалист по страхованию
главныцй бухгалтер
заместитель генерального директора
продавец
программист
специалист отдела кадров
специалист отдела продаж
заместитель начальника отдела
грузчик-наборщик
звукоинженер
зам. директора по кадровым вопросам
матрос
альпинист
курьер
руководитель направления
художник
индивидуальный предприниматель
лаборант
исполнительный директор
финансовый директор
врач
зам. директора
водитель
маркетолог
врач анестезиолог реаниматолог
водителоь-экспедитор
артдиректор
инженер-программист
разработчик аппаратных средств
редактор сайта gameland.ru
вед.специалист эксперт
бухгалтер
администратор
старший тех специалист
мастер механик
дизайнер
ведущий специалист
начальник участка
зам.финансового директора


In [213]:
data_itog.APP_TRAVEL_PASS.equals(data_itog.APP_DRIVING_LICENSE)

False

In [214]:
data_itog.APP_TRAVEL_PASS.equals(data_itog.APP_CAR)

False

In [215]:
data_itog.APP_DRIVING_LICENSE.equals(data_itog.APP_CAR)

False

In [216]:
data_itog.APP_COMP_TYPE.equals(data_itog.APP_EMP_TYPE)

True

In [217]:
data_itog.drop(columns=['APP_EMP_TYPE'])

ID  AMOUNT_RUB_ATM_PRC  AMOUNT_RUB_CLO_PRC  AMOUNT_RUB_NAS_PRC  \
0       146841            1.000000            0.000000            0.000000   
1       146842            0.410691            0.041033            0.000000   
2       146843            0.925140            0.006915            0.000000   
3       146844            1.000000            0.000000            0.000000   
4       146845            1.000000            0.000000            0.000000   
...        ...                 ...                 ...                 ...   
355185  590822            0.786104            0.000000            0.000000   
355186  590823            0.000000            0.000000            0.262714   
355187  590825            0.000000            0.041298            0.031179   
355188  590826            0.717427            0.000000            0.282573   
355189  590828            1.000000            0.000000            0.000000   

        AMOUNT_RUB_SUP_PRC  CNT_TRAN_ATM_TENDENCY1M  CNT_TRAN_ATM_TENDENCY3M  \
0                 0.000000                 0.101695                 0.406780   
1                 0.244678                 0.166667                 0.333333   
2                 0.000000                 0.133333                 0.366667   
3                 0.000000                      NaN                      NaN   
4                 0.000000                 0.172414                 0.620690   
...                    ...                      ...                      ...   
355185            0.000000                      NaN                 0.500000   
355186            0.000000                      NaN                      NaN   
355187            0.095187                      NaN                      NaN   
355188            0.000000                 0.250000                 1.000000   
355189            0.000000                      NaN                      NaN   

        CNT_TRAN_AUT_TENDENCY1M  CNT_TRAN_AUT_TENDENCY3M  \
0                           NaN                      NaN   
1                      0.166667                 0.666667   
2                           NaN                      NaN   
3                           NaN                      NaN   
4                           NaN                      NaN   
...                         ...                      ...   
355185                 0.142857                 1.000000   
355186                      NaN                      NaN   
355187                 0.089286                 0.392857   
355188                      NaN                      NaN   
355189                      NaN                      NaN   

        CNT_TRAN_CLO_TENDENCY1M  ...  CNT_ACCEPTS_MTP  CNT_ACCEPTS_TK  \
0                           NaN  ...              NaN             NaN   
1                           NaN  ...              NaN             NaN   
2                           NaN  ...              0.0             0.0   
3                           NaN  ...              NaN             NaN   
4                           NaN  ...              NaN             NaN   
...                         ...  ...              ...             ...   
355185                      NaN  ...              0.0             0.0   
355186                      NaN  ...              0.0             0.0   
355187                      NaN  ...              NaN             NaN   
355188                      NaN  ...              NaN             NaN   
355189                      NaN  ...              NaN             NaN   

        PRC_ACCEPTS_A_AMOBILE  PRC_ACCEPTS_A_ATM  PRC_ACCEPTS_A_EMAIL_LINK  \
0                         NaN                NaN                       NaN   
1                         NaN                NaN                       NaN   
2                         0.0                0.0                       0.0   
3                         NaN                NaN                       NaN   
4                         NaN                NaN                       NaN   
...                       ...                ...

8. Выведите колонки итогового датасета

In [218]:
for x in data_itog.axes[1]:
    print (x) 

ID
AMOUNT_RUB_ATM_PRC
AMOUNT_RUB_CLO_PRC
AMOUNT_RUB_NAS_PRC
AMOUNT_RUB_SUP_PRC
CNT_TRAN_ATM_TENDENCY1M
CNT_TRAN_ATM_TENDENCY3M
CNT_TRAN_AUT_TENDENCY1M
CNT_TRAN_AUT_TENDENCY3M
CNT_TRAN_CLO_TENDENCY1M
CNT_TRAN_CLO_TENDENCY3M
CNT_TRAN_MED_TENDENCY1M
CNT_TRAN_MED_TENDENCY3M
CNT_TRAN_SUP_TENDENCY1M
CNT_TRAN_SUP_TENDENCY3M
SUM_TRAN_ATM_TENDENCY1M
SUM_TRAN_ATM_TENDENCY3M
SUM_TRAN_AUT_TENDENCY1M
SUM_TRAN_AUT_TENDENCY3M
SUM_TRAN_CLO_TENDENCY1M
SUM_TRAN_CLO_TENDENCY3M
SUM_TRAN_MED_TENDENCY1M
SUM_TRAN_MED_TENDENCY3M
SUM_TRAN_SUP_TENDENCY1M
SUM_TRAN_SUP_TENDENCY3M
TRANS_AMOUNT_TENDENCY3M
TRANS_CNT_TENDENCY3M
TRANS_COUNT_ATM_PRC
TRANS_COUNT_NAS_PRC
TRANS_COUNT_SUP_PRC
AGE
APP_CAR
APP_COMP_TYPE
APP_DRIVING_LICENSE
APP_EDUCATION
APP_EMP_TYPE
APP_KIND_OF_PROP_HABITATION
APP_MARITAL_STATUS
APP_POSITION_TYPE
APP_REGISTR_RGN_CODE
APP_TRAVEL_PASS
AVG_PCT_DEBT_TO_DEAL_AMT
AVG_PCT_MONTH_TO_PCLOSE
DEAL_GRACE_DAYS_ACC_AVG
DEAL_GRACE_DAYS_ACC_MAX
DEAL_GRACE_DAYS_ACC_S1X1
DEAL_YQZ_IR_MAX
DEAL_YQZ_IR_MIN
DEAL_YW